### ISSUE TITLE
Event?

### ISSUE THREAD

**Issue by xhsien** [CS2103AUG2017-T13-B2/main#70]
![image](https://user-images.githubusercontent.com/7839537/32362954-c393dba8-c0a7-11e7-95c3-25033ec0140d.png)

Am I supposed to be able to edit the event? I can't find it in UserGuide

**Comment by yunpengn** [comment]
where can i open this interface actually?

**Comment by xhsien** [comment]
select on the person

**Comment by siri99** [comment]
Only an interface as of now, events class to be implemented in V2.0
