### ISSUE TITLE
Cannot add person

### ISSUE THREAD

**Issue by kyngyi** [CS2103AUG2017-T13-B2/main#71]
command just doesnt work

**Comment by xhsien** [comment]
Can you leave a screenshot? It works for me.
![image](https://user-images.githubusercontent.com/7839537/32363274-7edc8328-c0a9-11e7-991f-f6c29fd3c493.png)

**Comment by kyngyi** [comment]
it doesnt throw an error message when i leave out the "s/" value

**Comment by kyngyi** [comment]
Wasnt that i cant add mybad

**Comment by siri99** [comment]
Sort command is optional. Will not throw error when leaving out s/ value. Thanks!
