### ISSUE TITLE
Ui.png is missing

### ISSUE THREAD

**Issue by damithc** [CS2103AUG2017-T13-B2/main#99]
Your UI screenshot is not appearing in our [project list page](https://nus-cs2103.github.io/website/admin/projectList.html)

**Comment by siri99** [comment]
Just checked, UI screenshot is appearing:
![image](https://user-images.githubusercontent.com/29172477/32611807-8f656816-c5a1-11e7-9e17-ba6fd9c0135f.png)
Thanks Prof

**Comment by LinusMelb** [comment]
I'll deal with it now!
